### ISSUE TITLE
Admin side doesn't like SiteSettings

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/MetadataBrowse#17]
Looks like I need to check admin or public side before looking up SiteSettings

```
Omeka\Service\Exception\RuntimeException: Cannot use site settings when no site is set in /var/www/omekas/application/src/Settings/SiteSettings.php:38
Stack trace:
#0 /var/www/omekas/application/src/Settings/AbstractSettings.php(158): Omeka\Settings\SiteSettings->setCache()
#1 /var/www/omekas/application/src/Settings/AbstractSettings.php(104): Omeka\Settings\AbstractSettings->cache()
#2 /var/www/omekas/modules/MetadataBrowse/Module.php(74): Omeka\Settings\AbstractSettings->get('metadata_browse...')
#3 [internal function]: MetadataBrowse\Module->repValueHtml(Object(Zend\EventManager\Event))
#4 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\EventManager\Event))
#5 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(214): Zend\EventManager\EventManager->triggerListeners('rep.value.html', Object(Zend\EventManager\Event), NULL)
#6 /var/www/omekas/application/src/Api/Representation/ValueRepresentation.php(56): Zend\EventManager\EventManager->trigger('rep.value.html', Object(Omeka\Api\Representation\ValueRepresentation), Object(ArrayObject))
#7 /var/www/omekas/application/view-shared/common/resource-values.phtml(37): Omeka\Api\Representation\ValueRepresentation->asHtml()
#8 /var/www/omekas/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(502): include('/var/www/omekas...')
#9 /var/www/omekas/vendor/zendframework/zend-view/src/Helper/Partial.php(61): Zend\View\Renderer\PhpRenderer->render(Array)
#10 /var/www/omekas/application/src/Api/Representation/AbstractResourceEntityRepresentation.php(401): Zend\View\Helper\Partial->__invoke('common/resource...', Array)
#11 /var/www/omekas/application/view-admin/omeka/admin/item/show.phtml(31): Omeka\Api\Representation\AbstractResourceEntityRepresentation->displayValues()
#12 /var/www/omekas/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(502): include('/var/www/omekas...')
#13 /var/www/omekas/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render()
#14 /var/www/omekas/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#15 /var/www/omekas/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#16 /var/www/omekas/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#17 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#18 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#19 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(251): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent))
#20 /var/www/omekas/vendor/zendframework/zend-mvc/src/Application.php(384): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#21 /var/www/omekas/vendor/zendframework/zend-mvc/src/Application.php(356): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#22 /var/www/omekas/index.php(17): Zend\Mvc\Application->run()
#23 {main}
```

**Comment by patrickmj** [comment]
The change to make it work on the public side created this regression. On admin side, at least as global admin, site contexts don't exist, so the attempt to get it to work for public side fails because there's no site.

Thus, need to decide about different functionality between admin and public side. Should admin side follow a reintroduced global config, or should metadata browse just not be present on the admin side?

**Comment by patrickmj** [comment]
Alternative approach would be to have the admin side apply _all_ the configs from all the sites, which seems kooky, but could be on the table.
